Cafe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from cafe_site.sitemaps import StaticViewSitemap
from  menu.sitemaps import MenuSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    "static": StaticViewSitemap,
    "menu": MenuSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cafe_site.urls')),
    path('menu/', include('menu.urls')),
    path('captcha/', include('captcha.urls')),
    path('summernote/', include('django_summernote.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe_site/urls.py
from django.urls import path
from cafe_site import views


app_name = 'cafe_site'

urlpatterns = [path('', views.index,  name='home'),
               path('contact/', views.contact, name='contact'),
               path('about/', views.about, name='about'),
]

menu/urls.py
from django.urls import path
from menu import views


app_name = 'menu'

urlpatterns = [path('', views.index,  name='menu'),

]

cafe_site/models.py
from django.db import models


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(null=False, blank=False)
    subject = models.CharField(max_length=255, blank=False)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.email

    class Meta:
        ordering = ['-created_date']

menu/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    #  define status choices for status field in model
    STATUS_CHOICES = [
        ('available', 'Available'),
        ('sold_out', 'Sold Out'),
        ('coming_soon', 'Coming Soon')]
    image = models.ImageField(upload_to='menu/', null=True, blank=True)
    name = models.CharField(max_length=255)
    price = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    status = models.CharField(max_length=50, default='coming_soon', choices=STATUS_CHOICES)
    created_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True)

    def save(self, *args, **kwargs):
        # Call the original save method to save the image first
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        # Set a uniform size for all images
        desired_size = (136, 136)  # Set your desired size here

        # Resize the image while maintaining aspect ratio
        img = img.resize(desired_size)

        img.save(self.image.path)

    class Meta:
        ordering = ['-created_date']

cafe_site/forms.py
from django import forms
from cafe_site.models import Contact
from captcha.fields import CaptchaField


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Contact
        fields = '__all__'

cafe_site/views.py
from django.contrib import messages
from django.shortcuts import render
from cafe_site.forms import ContactForm


# Create your views here.
def index(request):
    return render(request, 'index.html')


def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message has been sent successfully!')
        else:
            messages.error(request, 'There was an error sending your message.')
    form = ContactForm()
    context = {'form': form}
    return render(request, 'contact.html', context)


def about(request):
    return render(request, 'about.html')

menu/views.py
from django.db.models import Prefetch
from django.shortcuts import render
from django.utils import timezone
from .models import Product, Category


# Create your views here.

def index(request):
    # Fetch categories and prefetch their products, filter products based on status and published_date
    categories = Category.objects.prefetch_related(Prefetch('products', queryset=Product.objects.
        filter(status__in=('coming_soon', 'available'), published_date__lte=timezone.now()).order_by('name'))).order_by(
        'name')
    # Filter out categories that don't have any available products
    categories_with_products = [category for category in categories if category.products.exists()]
    # Pass the filtered categories to the template
    context = {'categories': categories_with_products, 'all_categories': categories}
    return render(request, 'menu/menu.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cafe House</title>
<!-- 
Cafe House Template
http://www.templatemo.com/tm-466-cafe-house
-->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/templatemo-style.css' %}" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    <!-- Preloader -->
    <div id="loader-wrapper">
      <div id="loader"></div>
      <div class="loader-section section-left"></div>
      <div class="loader-section section-right"></div>
    </div>
    <!-- End Preloader -->
        <div class="tm-top-header">
      <div class="container">
        <div class="row">
          <div class="tm-top-header-inner">
            <div class="tm-logo-container">
              <img src="{% static 'img/logo.png' %}" alt="Logo" class="tm-site-logo">
              <h1 class="tm-site-name tm-handwriting-font">Cafe House</h1>
            </div>
            <div class="mobile-menu-icon">
              <i class="fa fa-bars"></i>
            </div>
            <nav class="tm-nav">
              <ul>
                <li><a href="{% url 'cafe_site:home' %}" >Home</a></li>
                <li><a href="{% url 'menu:menu' %}">Menu</a></li>
                <li><a href="{% url 'cafe_site:about' %}">About</a></li>
                <li><a href="{% url 'cafe_site:contact' %}">Contact</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>


{% block content %} {% endblock %}


    <footer>
      <div class="tm-black-bg">
        <div class="container">
          <div class="row margin-bottom-60">
            <nav class="col-lg-3 col-md-3 tm-footer-nav tm-footer-div">
              <h3 class="tm-footer-div-title">Main Menu</h3>
              <ul>
                <li><a href="{% url 'cafe_site:home' %}">Home</a></li>
                <li><a href="{% url 'cafe_site:about' %}">About Us</a></li>
                <li><a href="#directory">Directory</a></li>
              </ul>
            </nav>
            <div class="col-lg-5 col-md-5 tm-footer-div">
              <h3 class="tm-footer-div-title" id="directory">Directory</h3>
              <p class="margin-top-15">Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet.</p>
              <p class="margin-top-15">Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.</p>
            </div>
            <div class="col-lg-4 col-md-4 tm-footer-div">
              <h3 class="tm-footer-div-title">Get Social</h3>
              <p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante.</p>
              <div class="tm-social-icons-container">
                <a href="#" class="tm-social-icon"><i class="fa fa-facebook"></i></a>
                <a href="#" class="tm-social-icon"><i class="fa fa-twitter"></i></a>
                <a href="#" class="tm-social-icon"><i class="fa fa-linkedin"></i></a>
                <a href="#" class="tm-social-icon"><i class="fa fa-youtube"></i></a>
                <a href="#" class="tm-social-icon"><i class="fa fa-behance"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
        <div class="container">
          <div class="row tm-copyright">
           <p class="col-lg-12 small copyright-text text-center">Copyright &copy; 2084 Your Cafe House</p>
         </div>
       </div>
     </div>
   </footer> <!-- Footer content-->
   <!-- JS -->
   <script type="text/javascript" src="{% static 'js/jquery-1.11.2.min.js' %}"></script>      <!-- jQuery -->
   <script type="text/javascript" src="{% static 'js/templatemo-script.js' %}"></script>      <!-- Templatemo Script -->

 </body>
 </html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Enhanced Popup Modal -->
<div id="message-popup" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p id="modal-message-content"></p>
    </div>
</div>

<!-- Hidden Div for Django Messages -->
<div id="popup-messages" style="display: none;">
    {% if messages %}
        {% for message in messages %}
            <p class="{{ message.tags }}">{{ message }}</p>
        {% endfor %}
    {% endif %}
</div>
<section class="tm-welcome-section">
  <div class="container tm-position-relative">
    <div class="tm-lights-container">
      <img src="{% static 'img/light.png' %}" alt="Light" class="light light-1">
      <img src="{% static 'img/light.png' %}" alt="Light" class="light light-2">
      <img src="{% static 'img/light.png' %}" alt="Light" class="light light-3">
    </div>
    <div class="row tm-welcome-content">
      <h2 class="white-text tm-handwriting-font tm-welcome-header"><img src="{% static 'img/header-line.png' %}" alt="Line" class="tm-header-line">&nbsp;Contact Us&nbsp;&nbsp;<img src="{% static 'img/header-line.png' %}" alt="Line" class="tm-header-line"></h2>
      <h2 class="gold-text tm-welcome-header-2">Cafe House</h2>
      <p class="gray-text tm-welcome-description">Cafe House is free <span class="gold-text">responsive Bootstrap</span> v3.3.5 layout by <span class="gold-text">templatemo</span>. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
      <a href="#main" class="tm-more-button tm-more-button-welcome">Message Us</a>
    </div>
    <img src="{% static 'img/table-set.png' %}" alt="Table Set" class="tm-table-set img-responsive">
  </div>
</section>
<div class="tm-main-section light-gray-bg">
    <div class="container" id="main">
        <section class="tm-section row">
            <h2 class="col-lg-12 margin-bottom-30">Send us a message</h2>
            <form action="{% url 'cafe_site:contact' %}" method="post" class="tm-contact-form">
                {% csrf_token %}
                <div class="col-lg-6 col-md-6">
                    <div class="form-group">
                        <input name="name" type="text" id="contact_name" class="form-control" placeholder="NAME" required />
                    </div>
                    <div class="form-group">
                        <input name="email" type="email" id="contact_email" class="form-control" placeholder="EMAIL" required />
                    </div>
                    <div class="form-group">
                        <input name="subject" type="text" id="contact_subject" class="form-control" placeholder="SUBJECT" required />
                    </div>
                    <div class="form-group">
                        <textarea name="message" id="contact_message" class="form-control" rows="6" placeholder="MESSAGE" required></textarea>
                    </div>

                    <!-- CAPTCHA Section -->
                    <div class="form-group" >
                        {{ form.captcha }}
                    </div>

                    <div class="form-group">
                        <button class="tm-more-button" type="submit" name="submit">Send message</button>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div id="google-map"></div>
                </div>
            </form>
        </section>
    </div>
</div>

<!-- JavaScript to Handle Popup -->
<script>
    window.onload = function() {
        var popupMessages = document.getElementById("popup-messages");
        if (popupMessages.innerHTML.trim() !== "") {
            var modal = document.getElementById("message-popup");
            var modalMessageContent = document.getElementById("modal-message-content");

            // Retrieve the messages from the hidden div
            modalMessageContent.innerHTML = popupMessages.innerHTML;

            // Show the modal with fade-in effect
            modal.style.display = "flex";
            modal.classList.add("fade-in");

            // Close the modal when the user clicks the close button
            document.querySelector(".close").onclick = function() {
                modal.classList.add("fade-out");
                setTimeout(function() {
                    modal.style.display = "none";
                    modal.classList.remove("fade-out");
                }, 500);  // Time for fade-out animation
            };

            // Automatically close the modal after 1 second
            setTimeout(function() {
                modal.classList.add("fade-out");
                setTimeout(function() {
                    modal.style.display = "none";
                    modal.classList.remove("fade-out");
                }, 500);  // Time for fade-out animation
            }, 3000);  // 3000ms = 3 second
        }
    };
</script>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="tm-welcome-section">
      <div class="container tm-position-relative">
        <div class="tm-lights-container">
          <img src="{% static 'img/light.png' %}" alt="Light" class="light light-1">
          <img src="{% static 'img/light.png' %}" alt="Light" class="light light-2">
          <img src="{% static 'img/light.png' %}" alt="Light" class="light light-3">
        </div>
        <div class="row tm-welcome-content">
          <h2 class="white-text tm-handwriting-font tm-welcome-header"><img src="{% static 'img/header-line.png' %}" alt="Line" class="tm-header-line">&nbsp;Welcome To&nbsp;&nbsp;<img src="{% static 'img/header-line.png' %}" alt="Line" class="tm-header-line"></h2>
          <h2 class="gold-text tm-welcome-header-2">Cafe House</h2>
          <p class="gray-text tm-welcome-description">Cafe House template is a mobile-friendly responsive <span class="gold-text">Bootstrap v3.3.5</span> layout by <span class="gold-text">templatemo</span>. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculusnec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p>
          <a href="#main" class="tm-more-button tm-more-button-welcome">Details</a>
        </div>
        <img src="{% static 'img/table-set.png' %}" alt="Table Set" class="tm-table-set img-responsive">
      </div>
    </section>
    <div class="tm-main-section light-gray-bg">
      <div class="container" id="main">
        <section class="tm-section row">
          <div class="col-lg-9 col-md-9 col-sm-8">
            <h2 class="tm-section-header gold-text tm-handwriting-font">The Best Coffee for you</h2>
            <h2>Cafe House</h2>
            <p class="tm-welcome-description">This is free HTML5 website template from <span class="blue-text">template</span><span class="green-text">mo</span>. Fndimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Ettiam sit amet orci eget eros faucibus tincidunt.</p>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-4 tm-welcome-img-container">
            <div class="inline-block shadow-img">
              <img src="{% static 'img/1.jpg' %}" alt="Image" class="img-circle img-thumbnail">
            </div>
          </div>
        </section>
        <section class="tm-section tm-section-margin-bottom-0 row">
          <div class="col-lg-12 tm-section-header-container">
            <h2 class="tm-section-header gold-text tm-handwriting-font"><img src="{% static 'img/logo.png' %}" alt="Logo" class="tm-site-logo"> Popular Items</h2>
            <div class="tm-hr-container"><hr class="tm-hr"></div>
          </div>
          <div class="col-lg-12 tm-popular-items-container">
            <div class="tm-popular-item">
              <img src="{% static 'img/popular-1.jpg' %}" alt="Popular" class="tm-popular-item-img">
              <div class="tm-popular-item-description">
                <h3 class="tm-handwriting-font tm-popular-item-title"><span class="tm-handwriting-font bigger-first-letter">a</span>mericano</h3><hr class="tm-popular-item-hr">
                <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque. sed ipsum.</p>
                <div class="order-now-container">
                  <a href="#" class="order-now-link tm-handwriting-font"></a>
                </div>
              </div>
            </div>
            <div class="tm-popular-item">
              <img src="{% static 'img/popular-2.jpg' %}" alt="Popular" class="tm-popular-item-img">
              <div class="tm-popular-item-description">
                <h3 class="tm-handwriting-font tm-popular-item-title"><span class="tm-handwriting-font bigger-first-letter">c</span>appuccino</h3><hr class="tm-popular-item-hr">
                <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque. sed ipsum.</p>
                <div class="order-now-container">
                  <a href="#" class="order-now-link tm-handwriting-font"></a>
                </div>
              </div>
            </div>
            <div class="tm-popular-item">
              <img src="{% static 'img/popular-3.jpg' %}" alt="Popular" class="tm-popular-item-img">
              <div class="tm-popular-item-description">
                <h3 class="tm-handwriting-font tm-popular-item-title"><span class="tm-handwriting-font bigger-first-letter">m</span>ocha</h3><hr class="tm-popular-item-hr">
                <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque. sed ipsum.</p>
                <div class="order-now-container">
                  <a href="#" class="order-now-link tm-handwriting-font"></a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="tm-section row">
          <div class="col-lg-12 tm-section-header-container">
            <h2 class="tm-section-header gold-text tm-handwriting-font"><img src="{% static 'img/logo.png' %}" alt="Logo" class="tm-site-logo"> Today's Special</h2>
            <div class="tm-hr-container"><hr class="tm-hr"></div>
          </div>
          <div class="col-lg-12 tm-special-container margin-top-60">
            <div class="tm-special-container-left"> <!-- left -->
              <div class="tm-special-item">
                <div class="tm-special-img-container">
                  <img src="{% static 'img/special-1.jpg' %}" alt="Special" class="tm-special-img img-responsive">
                    <div class="tm-special-description">
                      <h3 class="tm-special-title">Donec pede justo</h3>
                      <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
                    </div>
                </div>
              </div>
            </div>
            <div class="tm-special-container-right"> <!-- right -->
              <div>
                <div class="tm-special-item">
                  <div class="tm-special-img-container">
                    <img src="{% static 'img/special-2.jpg' %}" alt="Special" class="img-responsive">

                      <div class="tm-special-description">
                        <h3 class="tm-special-title">Etiam sit amet</h3>
                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
                      </div>

                  </div>
                </div>
              </div>
              <div class="tm-special-container-lower">
                <div class="tm-special-item">
                  <div class="tm-special-img-container">
                    <img src="{% static 'img/special-3.jpg' %}" alt="Special" class="img-responsive">

                      <div class="tm-special-description">
                        <p>Vivamus elementum</p>
                      </div>

                  </div>
                </div>
                <div class="tm-special-item">
                  <div class="tm-special-img-container">
                    <img src="{% static 'img/special-4.jpg' %}" alt="Special" class="img-responsive">

                      <div class="tm-special-description">
                        <p>Quisque rutrum.</p>
                      </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="tm-section">
          <div class="row">
            <div class="col-lg-12 tm-section-header-container">
              <h2 class="tm-section-header gold-text tm-handwriting-font"><img src="{% static 'img/logo.png' %}" alt="Logo" class="tm-site-logo"> Daily Menu</h2>
              <div class="tm-hr-container"><hr class="tm-hr"></div>
            </div>
          </div>
          <div class="row">
            <div class="tm-daily-menu-container margin-top-60">
              <div class="col-lg-4 col-md-4">
                <img src="{% static 'img/menu-board.png' %}" alt="Menu board" class="tm-daily-menu-img">
              </div>            
              <div class="col-lg-8 col-md-8">
                <p>Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.</p>
                <ol class="margin-top-30">
                  <li>Tellus eget condimentum rhoncus.</li> 
                  <li>Sem quam semper libero.</li>
                  <li>Sit amet adipiscing sem neque sed ipsum.</li> 
                  <li>Nam quam nunc, blandit vel, luctus pulvinar.</li> 
                  <li>Maecenas nec odio et ante tincidunt tempus.</li> 
                  <li>Donec vitae sapien ut libero ventenatis faucibus.</li> 
                </ol>
                <a href="{% url 'menu:menu' %}" class="tm-more-button margin-top-30">Read More</a>
              </div>
            </div>
          </div>          
        </section>
      </div>
    </div> 
{% endblock %}

templates/menu/menu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="tm-welcome-section">
      <div class="container tm-position-relative">
        <div class="tm-lights-container">
          <img src="{% static 'img/light.png' %}" alt="Light" class="light light-1">
          <img src="{% static 'img/light.png' %}" alt="Light" class="light light-2">
          <img src="{% static 'img/light.png' %}" alt="Light" class="light light-3">  
        </div>        
        <div class="row tm-welcome-content">
          <h2 class="white-text tm-handwriting-font tm-welcome-header"><img src="{% static 'img/header-line.png' %}" alt="Line" class="tm-header-line">&nbsp;Our Menus&nbsp;&nbsp;<img src="{% static 'img/header-line.png' %}" alt="Line" class="tm-header-line"></h2>
          <h2 class="gold-text tm-welcome-header-2">Cafe House</h2>
          <p class="gray-text tm-welcome-description">Cafe House template is a mobile-friendly responsive <span class="gold-text">Bootstrap v3.3.5 layout</span> by <span class="gold-text">templatemo</span>. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculusnec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p>
          <a href="#main" class="tm-more-button tm-more-button-welcome">Read More</a>      
        </div>
        <img src="{% static 'img/table-set.png' %}" alt="Table Set" class="tm-table-set img-responsive">  
      </div>      
    </section>
    <div class="tm-main-section light-gray-bg">
      <div class="container" id="main">
        <section class="tm-section row">
          <div class="col-lg-9 col-md-9 col-sm-8">
            <h2 class="tm-section-header gold-text tm-handwriting-font">Variety of Menus</h2>
            <h2>Cafe House</h2>
            <p class="tm-welcome-description">This is free HTML5 website template from <span class="blue-text">template</span><span class="green-text">mo</span>. Fndimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Ettiam sit amet orci eget eros faucibus tincidunt.</p>
            <a href="{% url 'cafe_site:about' %}" class="tm-more-button margin-top-30">Read More</a>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-4 tm-welcome-img-container">
            <div class="inline-block shadow-img">
              <img src="{% static 'img/1.jpg' %}" alt="Image" class="img-circle img-thumbnail">  
            </div>              
          </div>            
        </section>          
        <section class="tm-section row">
          <div class="col-lg-12 tm-section-header-container margin-bottom-30">
            <h2 class="tm-section-header gold-text tm-handwriting-font"><img src="{% static 'img/logo.png' %}" alt="Logo" class="tm-site-logo"> Our Menus</h2>
            <div class="tm-hr-container"><hr class="tm-hr"></div>
          </div>
          <div>
            <div class="col-lg-3 col-md-3">
              <div class="tm-position-relative margin-bottom-30">              
                <nav class="tm-side-menu">
                  {% for category in all_categories %}
                  <ul>
                    <li><a href="#{{ category.name|slugify }}" class="active">{{category.name}}</a></li>
                  </ul>
                  {% endfor %}
                </nav>    
                <img src="{% static 'img/vertical-menu-bg.png' %}" alt="Menu bg" class="tm-side-menu-bg">
              </div>  
            </div>            
            <div class="tm-menu-product-content col-lg-9 col-md-9"> <!-- menu content -->
            {% for category in categories %}
                <div class="tm-product">
                    <section id="{{ category.name|slugify }}">
                    <div class="tm-product-text">
                        <h3 class="tm-product-title">{{ category.name }}</h3>
                    </div>
                    </section>
                </div>
            {% for product in category.products.all %}
              <div class="tm-product">
                  <img src="{{ product.image.url }}" alt="Product">
                  <div class="tm-product-text">
                      <h3 class="tm-product-title">{{ product.name }}</h3>
                      <p class="tm-product-description">
                      {{product.content}} </p>
                  </div>
                  <div class="tm-product-price">
                      <a href="#" class="tm-product-price-link tm-handwriting-font">
                          <span class="tm-product-price-currency">$</span>{{ product.price }}
                      </a>
                  </div>
              </div>
              {% endfor %}
              {% endfor %}
            </div>
        </section>
      </div>
    </div> 
{% endblock %}